coa/urls.py
from django.conf.urls.defaults import * 
from django.views.generic import DetailView, ListView
from coa.models import Account
from utils import *

urlpatterns = patterns('',
    (r'^$',
        ProtectedListView.as_view(
            queryset=Account.objects.order_by('category', 'accno'),
            context_object_name='accounts_list',
            template_name='coa/index.html')),
    (r'^accounts/$', 'coa.views.account_edit'),
    (r'^accounts/(?P<account_id>\d+)/$', 'coa.views.account_edit'),
    url(r'^(?P<pk>\d+)/delete/$',
        ProtectedDetailView.as_view(
            model=Account,
            template_name='results.html'),
        name='poll_results'),
#    (r'^(?P<poll_id>\d+)/vote/$', 'coa.views.vote'),
)

glipy/urls.py
from django.conf.urls.defaults import * 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from views import myinfo
admin.autodiscover()

from rest_framework import routers
from coa.views import AccountViewSet

router = routers.DefaultRouter()
router.register(r'account', AccountViewSet)
 
urlpatterns = patterns('',
    (r'^api/', include(router.urls)),
    (r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    (r'^$', include('dashboard.urls')),
    (r'^dashboard/', include('dashboard.urls')),
    (r'^coa/', include('coa.urls')),
    (r'^journal/', include('journal.urls')),
    (r'^contact/', include('contact.urls')),
    (r'^tax/', include('tax.urls')),
    (r'^doctype/', include('doctype.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^myinfo/$', myinfo),
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', 'dashboard.views.logout_view'),
)

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

journal/models.py
from django.db import models
from django.forms import ModelForm, Select, TextInput, DateInput
from coa.models import Account
from contact.models import Contact
from tax.models import Tax
from doctype.models import Doctype
import datetime
from django.forms.forms import BoundField


class Trans(models.Model):
    doctype = models.ForeignKey(Doctype)
    reference = models.CharField(max_length=64, null=False)
    description = models.CharField(max_length=256, null=False)
    #project = models.ForeignKey(Project)
    trans_date = models.DateTimeField()

def make_custom_datefield(f):
    formfield = f.formfield()
    if isinstance(f, models.DateField):
        formfield.widget.format = '%d/%m/%Y'
        formfield.widget.attrs.update({'class':'datePicker', 'readonly':'true'})
    return formfield

class TransForm(ModelForm):
    formfield_callback = make_custom_datefield
    class Meta:
        model = Trans
#        widgets = {
#            'doctype': Select(attrs={'class':'span2'}),
#            'reference': TextInput(attrs={ 'size':'80', 'placeholder':'reference number', 'class':'span5'}),
#            'description': TextInput(attrs={ 'size':'100', 'placeholder':'transaction description', 'class':'span5'}),
#        }

class Item(models.Model):
    trans = models.ForeignKey(Trans, blank=True, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account)
    debit = models.DecimalField(blank=True, null=True, max_digits=20, decimal_places=10)
    credit = models.DecimalField(blank=True, null=True, max_digits=20, decimal_places=10)
    currency = models.CharField(max_length=3, null=False, default='MXN')
    contact = models.ForeignKey(Contact, blank=True, null=True, on_delete=models.CASCADE)
    tax = models.ForeignKey(Tax, blank=True, null=True, on_delete=models.CASCADE)
    note = models.CharField(max_length=256, blank=True)

class ItemForm(ModelForm):
    class Meta:
        model = Item
        widgets = {
            'account': Select(attrs={'class':'span2'}),
            'debit': TextInput(attrs={ 'size':'50', 'placeholder':"$", 'class':'span2'}),
            'credit': TextInput(attrs={ 'size':'50', 'placeholder':"$", 'class':'span2'}),
            'currency': TextInput(attrs={ 'size':'40', 'class':'span2'}),
            'contact': Select(attrs={'class':'span2'}),
            'tax': Select(attrs={'class':'span2'}),
            'note': TextInput(attrs={ 'size':'50', 'placeholder':"note", 'class':'span2'}),
        }

class FieldSet(object):
    def __init__(self,form,fields,legend='',cls=None):
        self.form = form
        self.legend = legend
        self.fields = fields
        self.cls = cls
 
    def __iter__(self):
        for name in self.fields:
            field = self.form.fields[name]
            yield BoundField(self.form, field, name)

templates/report/index.html
{% extends "base.html" %}

{% block title %}Transactions{% endblock %}

		<div id="wrapper">
		{% block wrapper%}

			<div id="content" class="span14">
			{% block content %}
				{% if trans_list %}
						<table border=1>
						{% for trans in trans_list %}
								<tr>
									<td>{{ trans.doctype }}</td>
									<td><a href="/journal/entry/{{ trans.id }}/">{{ trans.reference }}</a></td>
									<td>{{ trans.description }}</td>
									<td>{{ trans.trans_date }}</td>
							 		<td><a href="/journal/entry/{{ trans.id }}/" class="btn small success">Edit</a></td>
           				<td><a href="/journal/entry/{{ trans.id }}/delete" class="btn small danger">Delete</a></td>
								</tr>
						{% endfor %}
						</table>
				{% else %}
						<p>No trans are available.</p>
				{% endif %}
			{% endblock %}
			</div>

			<div id="sidebar" class="span22">
			{% block sidebar %}
					<ul>
						<li><a href="/journal/entry/" class="btn success" >Add Trans</a></li>
						<li><a href="/contact/entry/" class="btn info" >Add Contact</a></li>
						<li><a href="/coa/accounts/" class="btn info" >Add Account</a></li>
					</ul>
			{% endblock %}
			</div>

		{% endblock %}
		</div>

templates/report/pandl.html
{% extends "base.html" %}

{% block title %}Transactions{% endblock %}

		<div id="wrapper">
		{% block wrapper%}

			<div id="content" class="span14">
			{% block content %}
				{% if trans_list %}
						<table border=1>
						{% for trans in trans_list %}
								<tr>
									<td>{{ trans.doctype }}</td>
									<td><a href="/journal/entry/{{ trans.id }}/">{{ trans.reference }}</a></td>
									<td>{{ trans.description }}</td>
									<td>{{ trans.trans_date }}</td>
							 		<td><a href="/journal/entry/{{ trans.id }}/" class="btn small success">Edit</a></td>
           				<td><a href="/journal/entry/{{ trans.id }}/delete" class="btn small danger">Delete</a></td>
								</tr>
						{% endfor %}
						</table>
				{% else %}
						<p>No trans are available.</p>
				{% endif %}
			{% endblock %}
			</div>

			<div id="sidebar" class="span22">
			{% block sidebar %}
					<ul>
						<li><a href="/journal/entry/" class="btn success" >Add Trans</a></li>
						<li><a href="/contact/entry/" class="btn info" >Add Contact</a></li>
						<li><a href="/coa/accounts/" class="btn info" >Add Account</a></li>
					</ul>
			{% endblock %}
			</div>

		{% endblock %}
		</div>